### ISSUE TITLE
Adding a license?

### ISSUE THREAD

**Issue by hr-oss** [Amberfall/Stall#1]
Howdy!

Love this game. I was curious, if you’d like to add a license to the repo? That way people don’t have to worry about getting sued if they use it😆

Here’s a tutorial on how to add one: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you !

**Comment by Amberfall** [comment]
Hi there, sorry it took me so long to address this issue! I'm thrilled that you enjoy this game so much and have added the license.

**Comment by hr-oss** [comment]
No worries at all! Awesome !! Thank you so much 😄
